{
  "uptime": [
    {
      "created_at": "2021-01-24T02:54:16",
      "updated_at": "2021-01-24T02:54:16",
      "html_url": "https://github.com/pulibrary/uptime/issues/60",
      "number": 60,
      "pull_request_html_url": null,
      "repository_html_url": "https://github.com/pulibrary/uptime",
      "repository_name": "uptime",
      "state": "open",
      "title": "ðŸ›‘ Confluence is down",
      "user_name": "Francis Kayiwa",
      "comments": [],
      "events": [
        {
          "actor_name": "Francis Kayiwa",
          "created_at": "2021-01-24T02:54:16",
          "type": "labeled"
        },
        {
          "actor_name": "Francis Kayiwa",
          "created_at": "2021-01-24T02:54:16",
          "type": "labeled"
        },
        {
          "actor_name": "Francis Kayiwa",
          "created_at": "2021-01-24T02:54:17",
          "type": "locked"
        }
      ],
      "pr_html_url": null,
      "action": "created"
    }
  ],
  "__meta__": {
    "issue_count": 1,
    "created_count": 1,
    "today": "2021-01-23T22:00:08",
    "yesterday": "2021-01-22T22:00:08"
  }
}