{
  "pul-the-hard-way": [
    {
      "created_at": "2021-12-19T16:14:25",
      "updated_at": "2021-12-19T16:14:25",
      "html_url": "https://github.com/pulibrary/pul-the-hard-way/pull/92",
      "number": 92,
      "pull_request_html_url": "https://github.com/pulibrary/pul-the-hard-way/pull/92",
      "repository_html_url": "https://github.com/pulibrary/pul-the-hard-way",
      "repository_name": "pul-the-hard-way",
      "state": "open",
      "title": "notes for confluence",
      "user_name": "Francis Kayiwa",
      "comments": [],
      "events": [],
      "pr_html_url": "https://github.com/pulibrary/pul-the-hard-way/pull/92",
      "action": "pull_request_open"
    }
  ],
  "uptime": [
    {
      "created_at": "2021-12-19T08:15:29",
      "updated_at": "2021-12-19T08:15:29",
      "html_url": "https://github.com/pulibrary/uptime/issues/293",
      "number": 293,
      "pull_request_html_url": null,
      "repository_html_url": "https://github.com/pulibrary/uptime",
      "repository_name": "uptime",
      "state": "closed",
      "title": "ðŸ›‘ Dataspace is down",
      "user_name": "Francis Kayiwa",
      "comments": [
        {
          "user_name": "Francis Kayiwa",
          "updated_at": "2021-12-19T08:36:08",
          "html_url": "https://github.com/pulibrary/uptime/issues/293#issuecomment-997350519",
          "body": "**Resolved:** Dataspace is back up in [`683d85c`](https://github.com/pulibrary/uptime/commit/683d85cfda7781fdd305f27c0a295dd01803bf3f\n)."
        }
      ],
      "events": [
        {
          "actor_name": "Francis Kayiwa",
          "created_at": "2021-12-19T08:15:29",
          "type": "labeled"
        },
        {
          "actor_name": "Francis Kayiwa",
          "created_at": "2021-12-19T08:15:29",
          "type": "labeled"
        },
        {
          "actor_name": "Francis Kayiwa",
          "created_at": "2021-12-19T08:15:30",
          "type": "locked"
        },
        {
          "actor_name": "Francis Kayiwa",
          "created_at": "2021-12-19T08:36:08",
          "type": "closed"
        }
      ],
      "pr_html_url": null,
      "action": "created"
    },
    {
      "created_at": "2021-12-19T07:29:53",
      "updated_at": "2021-12-19T07:29:53",
      "html_url": "https://github.com/pulibrary/uptime/issues/292",
      "number": 292,
      "pull_request_html_url": null,
      "repository_html_url": "https://github.com/pulibrary/uptime",
      "repository_name": "uptime",
      "state": "closed",
      "title": "ðŸ›‘ Confluence is down",
      "user_name": "Francis Kayiwa",
      "comments": [
        {
          "user_name": "Francis Kayiwa",
          "updated_at": "2021-12-19T09:37:15",
          "html_url": "https://github.com/pulibrary/uptime/issues/292#issuecomment-997357869",
          "body": "**Resolved:** Confluence is back up in [`05d233b`](https://github.com/pulibrary/uptime/commit/05d233b324bac690a1bef7b1a7f6689611f830ee\n)."
        }
      ],
      "events": [
        {
          "actor_name": "Francis Kayiwa",
          "created_at": "2021-12-19T07:29:53",
          "type": "labeled"
        },
        {
          "actor_name": "Francis Kayiwa",
          "created_at": "2021-12-19T07:29:53",
          "type": "labeled"
        },
        {
          "actor_name": "Francis Kayiwa",
          "created_at": "2021-12-19T07:29:54",
          "type": "locked"
        },
        {
          "actor_name": "Francis Kayiwa",
          "created_at": "2021-12-19T09:37:16",
          "type": "closed"
        }
      ],
      "pr_html_url": null,
      "action": "created"
    }
  ],
  "__meta__": {
    "issue_count": 3,
    "created_count": 2,
    "pull_request_open_count": 1,
    "today": "2021-12-19T22:00:03",
    "yesterday": "2021-12-18T22:00:03"
  }
}